fixtures:
  repositories:
    stdlib:
      repo: "https://github.com/puppetlabs/puppetlabs-stdlib.git"
      ref: "4.12.0"

# profile module layout, default include ntp module
    ntp:
      repo: "https://github.com/puppetlabs/puppetlabs-ntp.git"
      ref: "4.2.0"
  symlinks:
    profile_base: "#{source_dir}"
